### ISSUE TITLE
Introduce basic notifications on editor page

### ISSUE THREAD

**Issue by manuelroth** [nzzdev/Q-editor#108]
- Add the notifications column in editor page
- Add default info boxes for input types
- Make possible that the text is configurable based on the options object in tool schema

**Comment by manuelroth** [comment]
### Problem
- Currently we can only show a single notification per input field in the editor. This is intended behavior
- If there are multiple notifications available they get sorted by type (`low`, `medium`, `high`) and the notification with the highest priority gets displayed
- The current implementation doesn't allow to prioritize notifications of the same type. This can results in unintended behavior.
- Example: TooManyColumns (more than 5 columns) notification gets shown instead of ShouldBeLineChart (more than 15 columns) notification -> [example on q-beta](https://q-beta.st-staging.nzz.ch/editor/chart/35f54c8588eaa44ac9e91740f01e9fa7)

### Proposed Solution
- Currently a validation endpoint returns an object in the following form:
```json
{
  "showNotification": false,
  "priority": "medium"
}
```
- I propose to make the priority property an object:
```json
{
  "showNotification": false,
  "priority": {
     "type": "medium",
     "value": 1
  }
}
```
- The value property can be used to prioritize notifications of the same type
- So the notifications will be sorted by type (low, medium, high) and inside the notification type by priority value

@benib Would love to know what you think about this?

**Comment by benib** [comment]
@manuelroth seems legit. 👍 

While we are at it: I would make the text in the displayed notification part of this object as well so the tool can take the current values into account when forming the message. Like `15 colums are a lot, consider a line chart`).

**Comment by manuelroth** [comment]
> While we are at it: I would make the text in the displayed notification part of this object as well so the tool can take the current values into account when forming the message. Like 15 colums are a lot, consider a line chart).

Currently the notification messages are stored in the translation file. If we put the messages directly into the notification object we can not support different languages. I would love to support data-based notification messages, but don't have a good idea for supporting both yet. Need to think more about it.
