### ISSUE TITLE
Redirect to page after successful login

### ISSUE THREAD

**Issue by benib** [nzzdev/Q-editor#14]
### Description

When a user is redirected to the login page because of missing auth, she gets to index and not the page she initially requested before getting redirected to /login.

### Steps to Reproduce

1. Go to Q editor item preview page without valid auth
2. See that you are redirected to login page
3. See that you do not get to item preview page but to the index after successful login

**Comment by fuenkchen** [comment]
Solved by https://github.com/nzzdev/Q-editor/pull/20
