### ISSUE TITLE
Placeholder in title won't translate

### ISSUE THREAD

**Issue by philipkueng** [nzzdev/Q-editor#147]
If you are in a tool and try to change the language, the placeholders for "title" and "subtitle" won't translate. 

Example in Q-Charts.

**Comment by benib** [comment]
The problem is this:

- `.` is used as the default separator in i18next (used by aurelia-i18n)
- the solution is to use `&#46;` in the translation keys instead if we have to have a `.` in there

**Comment by benib** [comment]
see example in this commit: https://github.com/nzzdev/Q-chart/commit/d4b139abbfe64488fa860c51f1e6baad37778563
