### ISSUE TITLE
Remove briefing link in Q help page

### ISSUE THREAD

**Issue by philipkueng** [nzzdev/Q-editor#150]
According to Christian, the "Briefing-Formular" was deleted and still referenced in the Q help page

> Ich möchte eine Grafik aus Q auch im Print verwenden. Wie funktioniert das?
> Bitte sag der Infografik Bescheid, welche Grafik du in welcher Grösse gerne hättest. **_Am besten verwendest du dafür das Briefing-Formular._**

Therefore remove the link

**Comment by benib** [comment]
@philipkueng the help page content is configured in the Q server implementation. See here: https://github.com/nzzdev/Q-server-nzz/blob/dev/config/common/help.js#L30
