### ISSUE TITLE
Modify the schema-editor-files component so it can accept zip files

### ISSUE THREAD

**Issue by manuelroth** [nzzdev/Q-editor#153]
### Introduction
For the custom-code tool we need the files component to be able to accept a zip file. The idea is that it is possible to upload a zip file contain all code/markup/style/images for the project.

### Implementation
At the moment the files component is only able to handle single file uploads. The schema has to look like [this (example usage in q-quiz)](https://github.com/nzzdev/Q-quiz/blob/dev/resources/schema.json#L307). 

We want to be able to define the schema in the following way to upload a zip file:
```json
{
  "title": "Upload Zip file",
  "type": "object",
  "Q:type": "files",
  "Q:options": {
    "maxFiles": 1,
    "acceptedFiles": "application/zip",
    "fileProperties": {
      "url": "url"
    }
  }
}
```

Link to code for schema-editor-files component: https://github.com/nzzdev/Q-editor/blob/dev/client/src/elements/schema-editor/schema-editor-files.js

**Comment by benib** [comment]
What is the exact plan here?

1. Extract the files in Q-Editor before uploading to the server
2. Extract the files in Q-server before storing to S3
3. Store the zip file as is on S3

3. should be possible already with the `acceptedFiles` property that takes a MIME type and configures dropzone accordingly

Re 1. and 2.: I am not sure if the gain is worth the added complexity. I see that we should be able to handle uploading a folder somehow. Can we discuss this before spending too much time implementing the special zip handling?

**Comment by manuelroth** [comment]
I will close this because we decided to not implement uploading the project files using a zip file -> see https://github.com/nzzdev/Q-editor/issues/155 for more infos
