### ISSUE TITLE
(schema-editor) show required state of inputs using notifications

### ISSUE THREAD

**Issue by benib** [nzzdev/Q-editor#184]
### show required state of inputs using the notification system.

We have a system to show notifications based on the data. We want to use the same system to show required state of inputs.

<img width="1109" alt="screenshot 2018-10-26 at 12 29 38" src="https://user-images.githubusercontent.com/821875/47561193-dde5c480-d91a-11e8-85b7-49028d4b93d3.png">

**Comment by manuelroth** [comment]
### Problems
- _Hierarchy:_ All notifications should be shown in the notifications column
- _Overlay:_ Notifications sometimes overlay each other, if the form element is less tall than the notification
- _non-standard form elements (table, geojson-point):_ Currently there is not way to know if a value was added or not (we don't know when to show the required notification)

<img width="1132" alt="bildschirmfoto 2018-11-05 um 13 29 33" src="https://user-images.githubusercontent.com/1810384/47998433-97a11a00-e0ff-11e8-98ef-eecae494dccd.png">

#### Possible solutions
Hierarchy:
- Only show top level required notifications. Hence, ignore required properties inside of objects/arrays
- Implement a logic for child elements to push a notification into the top-level schema-editor-wrapper

Overlay:
- Make it possible to switch between overlaying notifications
- Change the design of notifications so they will never be taller than the form element
- Ignore it

non-standard form elements (table, geojson-point):
- Implement some special logic for non-standard form elements which checks if there was already a value added and send an invalid event if not.
- Ignore it

**Comment by benib** [comment]
Some Inputs

## Overlay
I think it's fine to reverse the stacking order and show the first notification on top, and all the following below. whenever an element gets the focus, it's notifications should be on top, so this probably needs the focus event bubbling up to set the stacking order (z-index).

## Hierarchy
Need to spend more thinking on this one.

## non-standard form elements (table, geojson-point):
What if we find a way so the schema-editor element can define how it is checked for required:
1. by the HTML Form Validation API
2. by some special method implemented on the schema-editor elements model
