### ISSUE TITLE
Remove the browser detection and "works only with chrome" warning

### ISSUE THREAD

**Issue by benib** [nzzdev/Q-editor#211]
### Description

All new versions of modern browsers support the features we need for Q editor. Therefore we can remove the warning message.

**Comment by manuelroth** [comment]
This code needs to be removed for this change -> https://github.com/nzzdev/Q-editor/search?q=isChrome+OR+browserSupportMessage&unscoped_q=isChrome+OR+browserSupportMessage

**Comment by philipkueng** [comment]
Safari and Firefox are not able to connect to the [google font service](https://fonts.googleapis.com/css?family=Roboto) and therefore throw an error. 
Can you reproduce this?
