### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by pierrefrance** [nzzdev/Q-editor#222]
### Description

Hello, apparently some translations strings are missing. 
http://www.clipular.com/posts/4739122282102784?k=kKdJ31QRl4sTf8fT9WLQFO--2R8

like : 
"Daten zum Herunterladen anbieten" 
Sources : Ajouter Quelle

**Comment by pierrefrance** [comment]
I didn't find these strings in the french locale file.

**Comment by manuelroth** [comment]
Hi @pierrefrance,
Translations in Q can be separated in two groups. There are [editor-specific translations](https://github.com/nzzdev/Q-editor/blob/dev/client/locales/fr/translation.json) and [tool-specific translations](https://github.com/nzzdev/Q-chart/blob/dev/resources/locales/fr/translation.json). The Q-Editor reads the [schema](https://github.com/nzzdev/Q-chart/blob/dev/resources/schema.json) / [translations](https://github.com/nzzdev/Q-chart/blob/dev/resources/locales/fr/translation.json)in `resources/locales/fr/translation.json) that the Q-Tool (like Q-Chart or Q-Table) provides and renders / translates the input fields in the editor.

So for example the string "Daten zum Herunterladen anbieten" can be translated by addeding an entry `"Daten zum Herunterladen anbieten": "Offre de données pour le téléchargement"` in the [Q-Chart tool ](https://github.com/nzzdev/Q-chart/blob/dev/resources/locales/fr/translation.json)in `resources/locales/fr/translation.json`

We are happy to accept [Pull-Requests](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) for new translations and corrections of the existing translations (we used Google Translate to translated the strings to French. I am sure there are a lot of mistakes 😅). If you have any questions I am happy to help.

Cheers,
Manuel

**Comment by pierrefrance** [comment]
Hello thanks, I've updated a bit these two files but the strings were overall ok already. So I'm not very confident the missing string will translate correctly.

**Comment by manuelroth** [comment]
I think I don't understand you correctly. For which string the translation doesn't work?- BTW for the special case of the "Add source"- Button Q currently doesn't have a solution for translation. We didn't have the time yet to come up with a proper solution for this case.

![Screenshot 2019-07-10 at 11 03 01](https://user-images.githubusercontent.com/1810384/60956075-64540200-a302-11e9-838b-f46cdce9adfa.png)

**Comment by pierrefrance** [comment]
Small punt - if we could come up with a solution for translating the buttons, it would really be cool.
