### ISSUE TITLE
Several Q tools seems missing

### ISSUE THREAD

**Issue by pierrefrance** [nzzdev/Q-editor#238]
### Description

Several Q tools available in the demo are not available once the github files are installed. 

These are the tools available on the demo : 
http://www.clipular.com/c/6409993459597312.png?k=PCjHKe57KrsW6IPNWkAUvZhlhJs

These are the tools we see in our installed Q editor : 
http://www.clipular.com/c/5329673515696128.png?k=2ES8b50wrA7YMvnf6zeNUpJZ8lQ

How can we add the rest of the tools ? We're coming to an intense moment with local french elections and it would be nice if Q could be all up and running for these events. 

Best,

PF

**Comment by manuelroth** [comment]
Hi @pierrefrance,
It's great to see that you are using Q in production. We are very happy that you decided to use Q. That's awesome 🎉

To your question:
- Infomap was discontinued. We will remove it from the demo page
- Table can be used. It's here: https://github.com/nzzdev/q-table
- The Poll Result, Party Slogan and the Coalition Calculation tools are all very specific to the Swiss election process. Therefore we have never open-sourced them.

Cheers,
Manuel

**Comment by pierrefrance** [comment]
Ah ok thanks for your reply.

The coalition calculation tool is configured for swiss election but many elections lead to coalitions and I think this tool could really be helpful for many newsrooms with a bit of tweaking. For example in France, in march, local elections will lead into coalitions, in order to govern the urban areas.

**Comment by manuelroth** [comment]
I understand. We have decided to open-source the other election tools under the MIT license:
- Poll Result: https://github.com/nzzdev/Q-poll-result
- Party Slogans: https://github.com/nzzdev/Q-party-slogans
- Coalition Calculation: https://github.com/nzzdev/Q-coalition-calculation

I hope they can help you covering the local elections.
