### ISSUE TITLE
ERROR [Q] notificationCheck failed

### ISSUE THREAD

**Issue by fromdusttilldawn** [nzzdev/Q-editor#292]
### Description

When editing an item of a tool (Q-Choropleth for example) there are a lot of errors thrown with the message `ERROR [Q] notificationCheck failed`.

### Steps to Reproduce

1. Open any Q-Choropleth item in edit mode
2. Open the developer tools
3. Open the console
4. There should already be around 10 errors with the message above.

### Additional Information

The errors never stop coming. The longer you have an item open in edit mode, and actually change stuff, the more errors of the same kind are thrown. This seems to affect the overall performance of the Q-Editor (it doesn't react as fast anymore).

I didn't check all the tools, but it looks like, that the Q-Choropleth tool produces the most of those errors.

It happens on test, stage and as well as on prod.

**Comment by manuelroth** [comment]
Thank you for the notice @fromdusttilldawn. I will have a look at this.

**Comment by manuelroth** [comment]
Fixed by https://github.com/nzzdev/Q-editor/pull/293. Rolled out in v6.3.3.
