### ISSUE TITLE
Add Q option to not indent objects and arrays

### ISSUE THREAD

**Issue by fuenkchen** [nzzdev/Q-editor#45]
For some form elements we may want to not indent objects or arrays within the form, e.g. in Q quiz images and article recommendation. Would be nice to have a special Q option or extend the already existing Q option `compact` for that purpose.

**Comment by benib** [comment]
Yeah, I'm not entirely happy with this grouping/2nd level object handling we have now. Would love to have a better solution that works.

I'd rather not invent another option regarding the styling but try to improve the existing `compact`.
