### ISSUE TITLE
Mobile width for all items in feed

### ISSUE THREAD

**Issue by fuenkchen** [nzzdev/Q-editor#76]
### Description

At the moment charts generated with vega are not being displayed in mobile width, instead there are wider and hence, have a scrollbar.

### Steps to Reproduce

1. Go to q.st.nzz.ch/feed
2. Search for a line chart (rendered with vega)

**Expected behavior:** Display line chart also in mobile width without scrollbar

**Actual behavior:** Line charts are too wide.

**Comment by benib** [comment]
fixed with 0b53bb8d3c8b41729e7c80d534dc257fe39d5bfa
